/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.js' */
"use strict";

module.exports = {
  configs: {
    recommended: require("./configs/recommended")
  },
  rules: {
    "no-deprecated-apis": require("./rules/no-deprecated-apis"),
    "prefer-native-array-methods": require("./rules/prefer-native-array-methods")
  }
};
