/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
  plugins: ["closure-library"],
  rules: {
    "closure-library/no-deprecated-apis": "error",
    "closure-library/prefer-native-array-methods": "error"
  }
};
